language: node_js
node_js:
- 8
after_script:
- npm run coveralls
env:
  global:
    secure: YaUxl+RwpbSeYnMvri1WRsaruzBoBuYwlgCePcONXhbk7jTdv+gkWXMqMxvYzuqY0nvaT+q9/6bUzgUgbHMDUpMbK9f/Yx8+zyBlRBO8MSeVTLmS1cHd9+hTGeDYIKN1NH1hF4XyzZlIzI6pqMq5ARgpVLdC6UKMvgYrkVKbRYADlu+hIYwZqJVO8RBz7sBj5E9ehVRP0XA4KkVtHNZVVNWs1d4YFV11HEUdsUw74SOXNhAg+guIrzOSc+Ochk/clp72crlTQqrGMjXPzIae6LQMMFMDwm4/4wbCv8a3Vhqi1srRhPDszhIHmXR5V6JhqtgBbSXLbv44dX1lVS+J+37kUUplfzD9c2fHfejQcCZXxo5ppj+V4UYyJOrMmKlaC4bwYZLHWuA0le6zZw5yiRiTxkJDhU6iIWCZBBdNcbJXSXBbSSNCWxutjIsESMeE4+DDE7GpttaH1LiZPLxdwlsLT1rvlsfDt1NnPM3sXe8xNPJzNHKCmYB2jhpADMDl00B1GgBhiObjlrdKlVbB4woV206+qgBuGMypBU99R0Ih7DFhdDkUV6ZZd8X31CDLSdSoulQNBqbyU/y9nLivUgGgLTpvq+fkT8UJ61kGl36p9gzj0ibhQnPIW286dYq8u7S9oLFtYi1hSFs7ZKzgng4XTX8YGCDQTKrreHrp4tQ=
